// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `VelocityCalculation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM.MIO;

public abstract class _MasterDisp extends Ice.ObjectImpl implements Master
{
    protected void
    ice_copyStateFrom(Ice.Object __obj)
        throws java.lang.CloneNotSupportedException
    {
        throw new java.lang.CloneNotSupportedException();
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::SITM::MIO::Master"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[1];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public final String getSystemStatus()
    {
        return getSystemStatus(null);
    }

    public final VelocityResult[] processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops)
    {
        return processHistoricalData(data, arcs, stops, null);
    }

    public final VelocityResult[] processStreamingData(StreamingWindow window)
    {
        return processStreamingData(window, null);
    }

    public final void registerWorker(WorkerPrx worker)
    {
        registerWorker(worker, null);
    }

    public final void unregisterWorker(WorkerPrx worker)
    {
        unregisterWorker(worker, null);
    }

    public static Ice.DispatchStatus ___registerWorker(Master __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        SITM.MIO.WorkerPrx worker = SITM.MIO.WorkerPrxHelper.__read(__is);
        __inS.endReadParams();
        __obj.registerWorker(worker, __current);
        __inS.__writeEmptyParams();
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___unregisterWorker(Master __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        SITM.MIO.WorkerPrx worker = SITM.MIO.WorkerPrxHelper.__read(__is);
        __inS.endReadParams();
        __obj.unregisterWorker(worker, __current);
        __inS.__writeEmptyParams();
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___processHistoricalData(Master __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        BusDatagram[] data;
        Arc[] arcs;
        Stop[] stops;
        data = BusDatagramSeqHelper.read(__is);
        arcs = ArcSeqHelper.read(__is);
        stops = StopSeqHelper.read(__is);
        __inS.endReadParams();
        VelocityResult[] __ret = __obj.processHistoricalData(data, arcs, stops, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        VelocityResultSeqHelper.write(__os, __ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___processStreamingData(Master __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.startReadParams();
        StreamingWindow window = null;
        window = StreamingWindow.__read(__is, window);
        __inS.endReadParams();
        VelocityResult[] __ret = __obj.processStreamingData(window, __current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        VelocityResultSeqHelper.write(__os, __ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    public static Ice.DispatchStatus ___getSystemStatus(Master __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        __inS.readEmptyParams();
        String __ret = __obj.getSystemStatus(__current);
        IceInternal.BasicStream __os = __inS.__startWriteParams(Ice.FormatType.DefaultFormat);
        __os.writeString(__ret);
        __inS.__endWriteParams(true);
        return Ice.DispatchStatus.DispatchOK;
    }

    private final static String[] __all =
    {
        "getSystemStatus",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "processHistoricalData",
        "processStreamingData",
        "registerWorker",
        "unregisterWorker"
    };

    public Ice.DispatchStatus __dispatch(IceInternal.Incoming in, Ice.Current __current)
    {
        int pos = java.util.Arrays.binarySearch(__all, __current.operation);
        if(pos < 0)
        {
            throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return ___getSystemStatus(this, in, __current);
            }
            case 1:
            {
                return ___ice_id(this, in, __current);
            }
            case 2:
            {
                return ___ice_ids(this, in, __current);
            }
            case 3:
            {
                return ___ice_isA(this, in, __current);
            }
            case 4:
            {
                return ___ice_ping(this, in, __current);
            }
            case 5:
            {
                return ___processHistoricalData(this, in, __current);
            }
            case 6:
            {
                return ___processStreamingData(this, in, __current);
            }
            case 7:
            {
                return ___registerWorker(this, in, __current);
            }
            case 8:
            {
                return ___unregisterWorker(this, in, __current);
            }
        }

        assert(false);
        throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, true);
        __os.endWriteSlice();
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        __is.endReadSlice();
    }

    public static final long serialVersionUID = 0L;
}
