// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `VelocityCalculation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM.MIO;

public interface _MasterOperations
{
    void registerWorker(WorkerPrx worker, Ice.Current __current);

    void unregisterWorker(WorkerPrx worker, Ice.Current __current);

    VelocityResult[] processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, Ice.Current __current);

    VelocityResult[] processStreamingData(StreamingWindow window, Ice.Current __current);

    String getSystemStatus(Ice.Current __current);
}
