// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `VelocityCalculation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM.MIO;

public class Arc implements java.lang.Cloneable, java.io.Serializable
{
    public String arcId;

    public String lineId;

    public String startStopId;

    public String endStopId;

    public int orderIndex;

    public double distance;

    public Arc()
    {
        arcId = "";
        lineId = "";
        startStopId = "";
        endStopId = "";
    }

    public Arc(String arcId, String lineId, String startStopId, String endStopId, int orderIndex, double distance)
    {
        this.arcId = arcId;
        this.lineId = lineId;
        this.startStopId = startStopId;
        this.endStopId = endStopId;
        this.orderIndex = orderIndex;
        this.distance = distance;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Arc _r = null;
        if(rhs instanceof Arc)
        {
            _r = (Arc)rhs;
        }

        if(_r != null)
        {
            if(arcId != _r.arcId)
            {
                if(arcId == null || _r.arcId == null || !arcId.equals(_r.arcId))
                {
                    return false;
                }
            }
            if(lineId != _r.lineId)
            {
                if(lineId == null || _r.lineId == null || !lineId.equals(_r.lineId))
                {
                    return false;
                }
            }
            if(startStopId != _r.startStopId)
            {
                if(startStopId == null || _r.startStopId == null || !startStopId.equals(_r.startStopId))
                {
                    return false;
                }
            }
            if(endStopId != _r.endStopId)
            {
                if(endStopId == null || _r.endStopId == null || !endStopId.equals(_r.endStopId))
                {
                    return false;
                }
            }
            if(orderIndex != _r.orderIndex)
            {
                return false;
            }
            if(distance != _r.distance)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::SITM::MIO::Arc");
        __h = IceInternal.HashUtil.hashAdd(__h, arcId);
        __h = IceInternal.HashUtil.hashAdd(__h, lineId);
        __h = IceInternal.HashUtil.hashAdd(__h, startStopId);
        __h = IceInternal.HashUtil.hashAdd(__h, endStopId);
        __h = IceInternal.HashUtil.hashAdd(__h, orderIndex);
        __h = IceInternal.HashUtil.hashAdd(__h, distance);
        return __h;
    }

    public Arc
    clone()
    {
        Arc c = null;
        try
        {
            c = (Arc)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(arcId);
        __os.writeString(lineId);
        __os.writeString(startStopId);
        __os.writeString(endStopId);
        __os.writeInt(orderIndex);
        __os.writeDouble(distance);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        arcId = __is.readString();
        lineId = __is.readString();
        startStopId = __is.readString();
        endStopId = __is.readString();
        orderIndex = __is.readInt();
        distance = __is.readDouble();
    }

    static public void
    __write(IceInternal.BasicStream __os, Arc __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public Arc
    __read(IceInternal.BasicStream __is, Arc __v)
    {
        if(__v == null)
        {
             __v = new Arc();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final Arc __nullMarshalValue = new Arc();

    public static final long serialVersionUID = -1568372879L;
}
