// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `VelocityCalculation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM.MIO;

public class BusDatagram implements java.lang.Cloneable, java.io.Serializable
{
    public String busId;

    public String lineId;

    public String tripId;

    public String stopId;

    public double odometer;

    public double latitude;

    public double longitude;

    public String datagramDate;

    public int eventType;

    public BusDatagram()
    {
        busId = "";
        lineId = "";
        tripId = "";
        stopId = "";
        datagramDate = "";
    }

    public BusDatagram(String busId, String lineId, String tripId, String stopId, double odometer, double latitude, double longitude, String datagramDate, int eventType)
    {
        this.busId = busId;
        this.lineId = lineId;
        this.tripId = tripId;
        this.stopId = stopId;
        this.odometer = odometer;
        this.latitude = latitude;
        this.longitude = longitude;
        this.datagramDate = datagramDate;
        this.eventType = eventType;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        BusDatagram _r = null;
        if(rhs instanceof BusDatagram)
        {
            _r = (BusDatagram)rhs;
        }

        if(_r != null)
        {
            if(busId != _r.busId)
            {
                if(busId == null || _r.busId == null || !busId.equals(_r.busId))
                {
                    return false;
                }
            }
            if(lineId != _r.lineId)
            {
                if(lineId == null || _r.lineId == null || !lineId.equals(_r.lineId))
                {
                    return false;
                }
            }
            if(tripId != _r.tripId)
            {
                if(tripId == null || _r.tripId == null || !tripId.equals(_r.tripId))
                {
                    return false;
                }
            }
            if(stopId != _r.stopId)
            {
                if(stopId == null || _r.stopId == null || !stopId.equals(_r.stopId))
                {
                    return false;
                }
            }
            if(odometer != _r.odometer)
            {
                return false;
            }
            if(latitude != _r.latitude)
            {
                return false;
            }
            if(longitude != _r.longitude)
            {
                return false;
            }
            if(datagramDate != _r.datagramDate)
            {
                if(datagramDate == null || _r.datagramDate == null || !datagramDate.equals(_r.datagramDate))
                {
                    return false;
                }
            }
            if(eventType != _r.eventType)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::SITM::MIO::BusDatagram");
        __h = IceInternal.HashUtil.hashAdd(__h, busId);
        __h = IceInternal.HashUtil.hashAdd(__h, lineId);
        __h = IceInternal.HashUtil.hashAdd(__h, tripId);
        __h = IceInternal.HashUtil.hashAdd(__h, stopId);
        __h = IceInternal.HashUtil.hashAdd(__h, odometer);
        __h = IceInternal.HashUtil.hashAdd(__h, latitude);
        __h = IceInternal.HashUtil.hashAdd(__h, longitude);
        __h = IceInternal.HashUtil.hashAdd(__h, datagramDate);
        __h = IceInternal.HashUtil.hashAdd(__h, eventType);
        return __h;
    }

    public BusDatagram
    clone()
    {
        BusDatagram c = null;
        try
        {
            c = (BusDatagram)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(busId);
        __os.writeString(lineId);
        __os.writeString(tripId);
        __os.writeString(stopId);
        __os.writeDouble(odometer);
        __os.writeDouble(latitude);
        __os.writeDouble(longitude);
        __os.writeString(datagramDate);
        __os.writeInt(eventType);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        busId = __is.readString();
        lineId = __is.readString();
        tripId = __is.readString();
        stopId = __is.readString();
        odometer = __is.readDouble();
        latitude = __is.readDouble();
        longitude = __is.readDouble();
        datagramDate = __is.readString();
        eventType = __is.readInt();
    }

    static public void
    __write(IceInternal.BasicStream __os, BusDatagram __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public BusDatagram
    __read(IceInternal.BasicStream __is, BusDatagram __v)
    {
        if(__v == null)
        {
             __v = new BusDatagram();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final BusDatagram __nullMarshalValue = new BusDatagram();

    public static final long serialVersionUID = -1236641935L;
}
