// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `VelocityCalculation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM.MIO;

public final class BusDatagramHolder extends Ice.Holder<BusDatagram>
{
    public
    BusDatagramHolder()
    {
    }

    public
    BusDatagramHolder(BusDatagram value)
    {
        super(value);
    }
}
