// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `VelocityCalculation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM.MIO;

/**
 * Provides type-specific helper functions.
 **/
public final class MasterPrxHelper extends Ice.ObjectPrxHelperBase implements MasterPrx
{
    private static final String __getSystemStatus_name = "getSystemStatus";

    public String getSystemStatus()
    {
        return getSystemStatus(null, false);
    }

    public String getSystemStatus(java.util.Map<String, String> __ctx)
    {
        return getSystemStatus(__ctx, true);
    }

    private String getSystemStatus(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__getSystemStatus_name);
        return end_getSystemStatus(begin_getSystemStatus(__ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_getSystemStatus()
    {
        return begin_getSystemStatus(null, false, false, null);
    }

    public Ice.AsyncResult begin_getSystemStatus(java.util.Map<String, String> __ctx)
    {
        return begin_getSystemStatus(__ctx, true, false, null);
    }

    public Ice.AsyncResult begin_getSystemStatus(Ice.Callback __cb)
    {
        return begin_getSystemStatus(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_getSystemStatus(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getSystemStatus(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_getSystemStatus(Callback_Master_getSystemStatus __cb)
    {
        return begin_getSystemStatus(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_getSystemStatus(java.util.Map<String, String> __ctx, Callback_Master_getSystemStatus __cb)
    {
        return begin_getSystemStatus(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_getSystemStatus(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_getSystemStatus(null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_getSystemStatus(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getSystemStatus(null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_getSystemStatus(java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_getSystemStatus(__ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_getSystemStatus(java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getSystemStatus(__ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_getSystemStatus(java.util.Map<String, String> __ctx, 
                                                  boolean __explicitCtx, 
                                                  boolean __synchronous, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getSystemStatus(__ctx, __explicitCtx, __synchronous, 
                                     new IceInternal.Functional_TwowayCallbackArg1<String>(__responseCb, __exceptionCb, __sentCb)
                                         {
                                             public final void __completed(Ice.AsyncResult __result)
                                             {
                                                 MasterPrxHelper.__getSystemStatus_completed(this, __result);
                                             }
                                         });
    }

    private Ice.AsyncResult begin_getSystemStatus(java.util.Map<String, String> __ctx, 
                                                  boolean __explicitCtx, 
                                                  boolean __synchronous, 
                                                  IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getSystemStatus_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__getSystemStatus_name, __cb);
        try
        {
            __result.prepare(__getSystemStatus_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            __result.writeEmptyParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public String end_getSystemStatus(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __getSystemStatus_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            String __ret;
            __ret = __is.readString();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __getSystemStatus_completed(Ice.TwowayCallbackArg1<String> __cb, Ice.AsyncResult __result)
    {
        SITM.MIO.MasterPrx __proxy = (SITM.MIO.MasterPrx)__result.getProxy();
        String __ret = null;
        try
        {
            __ret = __proxy.end_getSystemStatus(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __processHistoricalData_name = "processHistoricalData";

    public VelocityResult[] processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops)
    {
        return processHistoricalData(data, arcs, stops, null, false);
    }

    public VelocityResult[] processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, java.util.Map<String, String> __ctx)
    {
        return processHistoricalData(data, arcs, stops, __ctx, true);
    }

    private VelocityResult[] processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__processHistoricalData_name);
        return end_processHistoricalData(begin_processHistoricalData(data, arcs, stops, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops)
    {
        return begin_processHistoricalData(data, arcs, stops, null, false, false, null);
    }

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, java.util.Map<String, String> __ctx)
    {
        return begin_processHistoricalData(data, arcs, stops, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, Ice.Callback __cb)
    {
        return begin_processHistoricalData(data, arcs, stops, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_processHistoricalData(data, arcs, stops, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, Callback_Master_processHistoricalData __cb)
    {
        return begin_processHistoricalData(data, arcs, stops, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, java.util.Map<String, String> __ctx, Callback_Master_processHistoricalData __cb)
    {
        return begin_processHistoricalData(data, arcs, stops, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, 
                                                       Arc[] arcs, 
                                                       Stop[] stops, 
                                                       IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_processHistoricalData(data, arcs, stops, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, 
                                                       Arc[] arcs, 
                                                       Stop[] stops, 
                                                       IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_processHistoricalData(data, arcs, stops, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, 
                                                       Arc[] arcs, 
                                                       Stop[] stops, 
                                                       java.util.Map<String, String> __ctx, 
                                                       IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_processHistoricalData(data, arcs, stops, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, 
                                                       Arc[] arcs, 
                                                       Stop[] stops, 
                                                       java.util.Map<String, String> __ctx, 
                                                       IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_processHistoricalData(data, arcs, stops, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, 
                                                        Arc[] arcs, 
                                                        Stop[] stops, 
                                                        java.util.Map<String, String> __ctx, 
                                                        boolean __explicitCtx, 
                                                        boolean __synchronous, 
                                                        IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_processHistoricalData(data, arcs, stops, __ctx, __explicitCtx, __synchronous, 
                                           new IceInternal.Functional_TwowayCallbackArg1<SITM.MIO.VelocityResult[]>(__responseCb, __exceptionCb, __sentCb)
                                               {
                                                   public final void __completed(Ice.AsyncResult __result)
                                                   {
                                                       MasterPrxHelper.__processHistoricalData_completed(this, __result);
                                                   }
                                               });
    }

    private Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, 
                                                        Arc[] arcs, 
                                                        Stop[] stops, 
                                                        java.util.Map<String, String> __ctx, 
                                                        boolean __explicitCtx, 
                                                        boolean __synchronous, 
                                                        IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__processHistoricalData_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__processHistoricalData_name, __cb);
        try
        {
            __result.prepare(__processHistoricalData_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            BusDatagramSeqHelper.write(__os, data);
            ArcSeqHelper.write(__os, arcs);
            StopSeqHelper.write(__os, stops);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public VelocityResult[] end_processHistoricalData(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __processHistoricalData_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            VelocityResult[] __ret;
            __ret = VelocityResultSeqHelper.read(__is);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __processHistoricalData_completed(Ice.TwowayCallbackArg1<VelocityResult[]> __cb, Ice.AsyncResult __result)
    {
        SITM.MIO.MasterPrx __proxy = (SITM.MIO.MasterPrx)__result.getProxy();
        VelocityResult[] __ret = null;
        try
        {
            __ret = __proxy.end_processHistoricalData(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __processStreamingData_name = "processStreamingData";

    public VelocityResult[] processStreamingData(StreamingWindow window)
    {
        return processStreamingData(window, null, false);
    }

    public VelocityResult[] processStreamingData(StreamingWindow window, java.util.Map<String, String> __ctx)
    {
        return processStreamingData(window, __ctx, true);
    }

    private VelocityResult[] processStreamingData(StreamingWindow window, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__processStreamingData_name);
        return end_processStreamingData(begin_processStreamingData(window, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window)
    {
        return begin_processStreamingData(window, null, false, false, null);
    }

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, java.util.Map<String, String> __ctx)
    {
        return begin_processStreamingData(window, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, Ice.Callback __cb)
    {
        return begin_processStreamingData(window, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_processStreamingData(window, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, Callback_Master_processStreamingData __cb)
    {
        return begin_processStreamingData(window, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, java.util.Map<String, String> __ctx, Callback_Master_processStreamingData __cb)
    {
        return begin_processStreamingData(window, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, 
                                                      IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_processStreamingData(window, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, 
                                                      IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_processStreamingData(window, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, 
                                                      java.util.Map<String, String> __ctx, 
                                                      IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_processStreamingData(window, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, 
                                                      java.util.Map<String, String> __ctx, 
                                                      IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_processStreamingData(window, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_processStreamingData(StreamingWindow window, 
                                                       java.util.Map<String, String> __ctx, 
                                                       boolean __explicitCtx, 
                                                       boolean __synchronous, 
                                                       IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_processStreamingData(window, __ctx, __explicitCtx, __synchronous, 
                                          new IceInternal.Functional_TwowayCallbackArg1<SITM.MIO.VelocityResult[]>(__responseCb, __exceptionCb, __sentCb)
                                              {
                                                  public final void __completed(Ice.AsyncResult __result)
                                                  {
                                                      MasterPrxHelper.__processStreamingData_completed(this, __result);
                                                  }
                                              });
    }

    private Ice.AsyncResult begin_processStreamingData(StreamingWindow window, 
                                                       java.util.Map<String, String> __ctx, 
                                                       boolean __explicitCtx, 
                                                       boolean __synchronous, 
                                                       IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__processStreamingData_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__processStreamingData_name, __cb);
        try
        {
            __result.prepare(__processStreamingData_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            StreamingWindow.__write(__os, window);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public VelocityResult[] end_processStreamingData(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __processStreamingData_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            VelocityResult[] __ret;
            __ret = VelocityResultSeqHelper.read(__is);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __processStreamingData_completed(Ice.TwowayCallbackArg1<VelocityResult[]> __cb, Ice.AsyncResult __result)
    {
        SITM.MIO.MasterPrx __proxy = (SITM.MIO.MasterPrx)__result.getProxy();
        VelocityResult[] __ret = null;
        try
        {
            __ret = __proxy.end_processStreamingData(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __registerWorker_name = "registerWorker";

    public void registerWorker(WorkerPrx worker)
    {
        registerWorker(worker, null, false);
    }

    public void registerWorker(WorkerPrx worker, java.util.Map<String, String> __ctx)
    {
        registerWorker(worker, __ctx, true);
    }

    private void registerWorker(WorkerPrx worker, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_registerWorker(begin_registerWorker(worker, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_registerWorker(WorkerPrx worker)
    {
        return begin_registerWorker(worker, null, false, false, null);
    }

    public Ice.AsyncResult begin_registerWorker(WorkerPrx worker, java.util.Map<String, String> __ctx)
    {
        return begin_registerWorker(worker, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_registerWorker(WorkerPrx worker, Ice.Callback __cb)
    {
        return begin_registerWorker(worker, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_registerWorker(WorkerPrx worker, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_registerWorker(worker, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_registerWorker(WorkerPrx worker, Callback_Master_registerWorker __cb)
    {
        return begin_registerWorker(worker, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_registerWorker(WorkerPrx worker, java.util.Map<String, String> __ctx, Callback_Master_registerWorker __cb)
    {
        return begin_registerWorker(worker, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_registerWorker(WorkerPrx worker, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_registerWorker(worker, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_registerWorker(WorkerPrx worker, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_registerWorker(worker, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_registerWorker(WorkerPrx worker, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_registerWorker(worker, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_registerWorker(WorkerPrx worker, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_registerWorker(worker, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_registerWorker(WorkerPrx worker, 
                                                 java.util.Map<String, String> __ctx, 
                                                 boolean __explicitCtx, 
                                                 boolean __synchronous, 
                                                 IceInternal.Functional_VoidCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_registerWorker(worker, 
                                    __ctx, 
                                    __explicitCtx, 
                                    __synchronous, 
                                    new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_registerWorker(WorkerPrx worker, 
                                                 java.util.Map<String, String> __ctx, 
                                                 boolean __explicitCtx, 
                                                 boolean __synchronous, 
                                                 IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__registerWorker_name, __cb);
        try
        {
            __result.prepare(__registerWorker_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            SITM.MIO.WorkerPrxHelper.__write(__os, worker);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_registerWorker(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __registerWorker_name);
    }

    private static final String __unregisterWorker_name = "unregisterWorker";

    public void unregisterWorker(WorkerPrx worker)
    {
        unregisterWorker(worker, null, false);
    }

    public void unregisterWorker(WorkerPrx worker, java.util.Map<String, String> __ctx)
    {
        unregisterWorker(worker, __ctx, true);
    }

    private void unregisterWorker(WorkerPrx worker, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_unregisterWorker(begin_unregisterWorker(worker, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_unregisterWorker(WorkerPrx worker)
    {
        return begin_unregisterWorker(worker, null, false, false, null);
    }

    public Ice.AsyncResult begin_unregisterWorker(WorkerPrx worker, java.util.Map<String, String> __ctx)
    {
        return begin_unregisterWorker(worker, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_unregisterWorker(WorkerPrx worker, Ice.Callback __cb)
    {
        return begin_unregisterWorker(worker, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_unregisterWorker(WorkerPrx worker, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_unregisterWorker(worker, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_unregisterWorker(WorkerPrx worker, Callback_Master_unregisterWorker __cb)
    {
        return begin_unregisterWorker(worker, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_unregisterWorker(WorkerPrx worker, java.util.Map<String, String> __ctx, Callback_Master_unregisterWorker __cb)
    {
        return begin_unregisterWorker(worker, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_unregisterWorker(WorkerPrx worker, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_unregisterWorker(worker, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_unregisterWorker(WorkerPrx worker, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_unregisterWorker(worker, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_unregisterWorker(WorkerPrx worker, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_unregisterWorker(worker, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_unregisterWorker(WorkerPrx worker, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_unregisterWorker(worker, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_unregisterWorker(WorkerPrx worker, 
                                                   java.util.Map<String, String> __ctx, 
                                                   boolean __explicitCtx, 
                                                   boolean __synchronous, 
                                                   IceInternal.Functional_VoidCallback __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_unregisterWorker(worker, 
                                      __ctx, 
                                      __explicitCtx, 
                                      __synchronous, 
                                      new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_unregisterWorker(WorkerPrx worker, 
                                                   java.util.Map<String, String> __ctx, 
                                                   boolean __explicitCtx, 
                                                   boolean __synchronous, 
                                                   IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__unregisterWorker_name, __cb);
        try
        {
            __result.prepare(__unregisterWorker_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            SITM.MIO.WorkerPrxHelper.__write(__os, worker);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_unregisterWorker(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __unregisterWorker_name);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static MasterPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), MasterPrx.class, MasterPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static MasterPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), MasterPrx.class, MasterPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static MasterPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), MasterPrx.class, MasterPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static MasterPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), MasterPrx.class, MasterPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static MasterPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, MasterPrx.class, MasterPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static MasterPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, MasterPrx.class, MasterPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::SITM::MIO::Master"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, MasterPrx v)
    {
        __os.writeProxy(v);
    }

    public static MasterPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            MasterPrxHelper result = new MasterPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
