// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `VelocityCalculation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM.MIO;

public interface MasterPrx extends Ice.ObjectPrx
{
    public void registerWorker(Worker worker);

    public void registerWorker(Worker worker, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_registerWorker(Worker worker);

    public Ice.AsyncResult begin_registerWorker(Worker worker, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_registerWorker(Worker worker, Ice.Callback __cb);

    public Ice.AsyncResult begin_registerWorker(Worker worker, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_registerWorker(Worker worker, Callback_Master_registerWorker __cb);

    public Ice.AsyncResult begin_registerWorker(Worker worker, java.util.Map<String, String> __ctx, Callback_Master_registerWorker __cb);

    public Ice.AsyncResult begin_registerWorker(Worker worker, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_registerWorker(Worker worker, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_registerWorker(Worker worker, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_registerWorker(Worker worker, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public void end_registerWorker(Ice.AsyncResult __result);

    public void unregisterWorker(Worker worker);

    public void unregisterWorker(Worker worker, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_unregisterWorker(Worker worker);

    public Ice.AsyncResult begin_unregisterWorker(Worker worker, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_unregisterWorker(Worker worker, Ice.Callback __cb);

    public Ice.AsyncResult begin_unregisterWorker(Worker worker, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_unregisterWorker(Worker worker, Callback_Master_unregisterWorker __cb);

    public Ice.AsyncResult begin_unregisterWorker(Worker worker, java.util.Map<String, String> __ctx, Callback_Master_unregisterWorker __cb);

    public Ice.AsyncResult begin_unregisterWorker(Worker worker, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_unregisterWorker(Worker worker, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_unregisterWorker(Worker worker, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_unregisterWorker(Worker worker, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public void end_unregisterWorker(Ice.AsyncResult __result);

    public VelocityResult[] processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops);

    public VelocityResult[] processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops);

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, Ice.Callback __cb);

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, Callback_Master_processHistoricalData __cb);

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, Arc[] arcs, Stop[] stops, java.util.Map<String, String> __ctx, Callback_Master_processHistoricalData __cb);

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, 
                                                       Arc[] arcs, 
                                                       Stop[] stops, 
                                                       IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, 
                                                       Arc[] arcs, 
                                                       Stop[] stops, 
                                                       IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, 
                                                       Arc[] arcs, 
                                                       Stop[] stops, 
                                                       java.util.Map<String, String> __ctx, 
                                                       IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_processHistoricalData(BusDatagram[] data, 
                                                       Arc[] arcs, 
                                                       Stop[] stops, 
                                                       java.util.Map<String, String> __ctx, 
                                                       IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                       IceInternal.Functional_BoolCallback __sentCb);

    public VelocityResult[] end_processHistoricalData(Ice.AsyncResult __result);

    public VelocityResult[] processStreamingData(StreamingWindow window);

    public VelocityResult[] processStreamingData(StreamingWindow window, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window);

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, Ice.Callback __cb);

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, Callback_Master_processStreamingData __cb);

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, java.util.Map<String, String> __ctx, Callback_Master_processStreamingData __cb);

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, 
                                                      IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, 
                                                      IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                      IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, 
                                                      java.util.Map<String, String> __ctx, 
                                                      IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_processStreamingData(StreamingWindow window, 
                                                      java.util.Map<String, String> __ctx, 
                                                      IceInternal.Functional_GenericCallback1<VelocityResult[]> __responseCb, 
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                      IceInternal.Functional_BoolCallback __sentCb);

    public VelocityResult[] end_processStreamingData(Ice.AsyncResult __result);

    public String getSystemStatus();

    public String getSystemStatus(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getSystemStatus();

    public Ice.AsyncResult begin_getSystemStatus(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getSystemStatus(Ice.Callback __cb);

    public Ice.AsyncResult begin_getSystemStatus(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getSystemStatus(Callback_Master_getSystemStatus __cb);

    public Ice.AsyncResult begin_getSystemStatus(java.util.Map<String, String> __ctx, Callback_Master_getSystemStatus __cb);

    public Ice.AsyncResult begin_getSystemStatus(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getSystemStatus(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getSystemStatus(java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getSystemStatus(java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public String end_getSystemStatus(Ice.AsyncResult __result);
}
