// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `VelocityCalculation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM.MIO;

public class ProcessingTask implements java.lang.Cloneable, java.io.Serializable
{
    public String taskId;

    public BusDatagram[] datagrams;

    public Arc[] arcs;

    public Stop[] stops;

    public int totalWorkers;

    public int workerId;

    public ProcessingTask()
    {
        taskId = "";
    }

    public ProcessingTask(String taskId, BusDatagram[] datagrams, Arc[] arcs, Stop[] stops, int totalWorkers, int workerId)
    {
        this.taskId = taskId;
        this.datagrams = datagrams;
        this.arcs = arcs;
        this.stops = stops;
        this.totalWorkers = totalWorkers;
        this.workerId = workerId;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ProcessingTask _r = null;
        if(rhs instanceof ProcessingTask)
        {
            _r = (ProcessingTask)rhs;
        }

        if(_r != null)
        {
            if(taskId != _r.taskId)
            {
                if(taskId == null || _r.taskId == null || !taskId.equals(_r.taskId))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(datagrams, _r.datagrams))
            {
                return false;
            }
            if(!java.util.Arrays.equals(arcs, _r.arcs))
            {
                return false;
            }
            if(!java.util.Arrays.equals(stops, _r.stops))
            {
                return false;
            }
            if(totalWorkers != _r.totalWorkers)
            {
                return false;
            }
            if(workerId != _r.workerId)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::SITM::MIO::ProcessingTask");
        __h = IceInternal.HashUtil.hashAdd(__h, taskId);
        __h = IceInternal.HashUtil.hashAdd(__h, datagrams);
        __h = IceInternal.HashUtil.hashAdd(__h, arcs);
        __h = IceInternal.HashUtil.hashAdd(__h, stops);
        __h = IceInternal.HashUtil.hashAdd(__h, totalWorkers);
        __h = IceInternal.HashUtil.hashAdd(__h, workerId);
        return __h;
    }

    public ProcessingTask
    clone()
    {
        ProcessingTask c = null;
        try
        {
            c = (ProcessingTask)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(taskId);
        BusDatagramSeqHelper.write(__os, datagrams);
        ArcSeqHelper.write(__os, arcs);
        StopSeqHelper.write(__os, stops);
        __os.writeInt(totalWorkers);
        __os.writeInt(workerId);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        taskId = __is.readString();
        datagrams = BusDatagramSeqHelper.read(__is);
        arcs = ArcSeqHelper.read(__is);
        stops = StopSeqHelper.read(__is);
        totalWorkers = __is.readInt();
        workerId = __is.readInt();
    }

    static public void
    __write(IceInternal.BasicStream __os, ProcessingTask __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public ProcessingTask
    __read(IceInternal.BasicStream __is, ProcessingTask __v)
    {
        if(__v == null)
        {
             __v = new ProcessingTask();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final ProcessingTask __nullMarshalValue = new ProcessingTask();

    public static final long serialVersionUID = -1068847605L;
}
