// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `VelocityCalculation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM.MIO;

public class Stop implements java.lang.Cloneable, java.io.Serializable
{
    public String stopId;

    public double longitude;

    public double latitude;

    public String shortName;

    public String longName;

    public Stop()
    {
        stopId = "";
        shortName = "";
        longName = "";
    }

    public Stop(String stopId, double longitude, double latitude, String shortName, String longName)
    {
        this.stopId = stopId;
        this.longitude = longitude;
        this.latitude = latitude;
        this.shortName = shortName;
        this.longName = longName;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Stop _r = null;
        if(rhs instanceof Stop)
        {
            _r = (Stop)rhs;
        }

        if(_r != null)
        {
            if(stopId != _r.stopId)
            {
                if(stopId == null || _r.stopId == null || !stopId.equals(_r.stopId))
                {
                    return false;
                }
            }
            if(longitude != _r.longitude)
            {
                return false;
            }
            if(latitude != _r.latitude)
            {
                return false;
            }
            if(shortName != _r.shortName)
            {
                if(shortName == null || _r.shortName == null || !shortName.equals(_r.shortName))
                {
                    return false;
                }
            }
            if(longName != _r.longName)
            {
                if(longName == null || _r.longName == null || !longName.equals(_r.longName))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::SITM::MIO::Stop");
        __h = IceInternal.HashUtil.hashAdd(__h, stopId);
        __h = IceInternal.HashUtil.hashAdd(__h, longitude);
        __h = IceInternal.HashUtil.hashAdd(__h, latitude);
        __h = IceInternal.HashUtil.hashAdd(__h, shortName);
        __h = IceInternal.HashUtil.hashAdd(__h, longName);
        return __h;
    }

    public Stop
    clone()
    {
        Stop c = null;
        try
        {
            c = (Stop)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(stopId);
        __os.writeDouble(longitude);
        __os.writeDouble(latitude);
        __os.writeString(shortName);
        __os.writeString(longName);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        stopId = __is.readString();
        longitude = __is.readDouble();
        latitude = __is.readDouble();
        shortName = __is.readString();
        longName = __is.readString();
    }

    static public void
    __write(IceInternal.BasicStream __os, Stop __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public Stop
    __read(IceInternal.BasicStream __is, Stop __v)
    {
        if(__v == null)
        {
             __v = new Stop();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final Stop __nullMarshalValue = new Stop();

    public static final long serialVersionUID = -1185584030L;
}
