// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `VelocityCalculation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM.MIO;

public class StreamingWindow implements java.lang.Cloneable, java.io.Serializable
{
    public String windowId;

    public BusDatagram[] datagrams;

    public long startTimestamp;

    public long endTimestamp;

    public StreamingWindow()
    {
        windowId = "";
    }

    public StreamingWindow(String windowId, BusDatagram[] datagrams, long startTimestamp, long endTimestamp)
    {
        this.windowId = windowId;
        this.datagrams = datagrams;
        this.startTimestamp = startTimestamp;
        this.endTimestamp = endTimestamp;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        StreamingWindow _r = null;
        if(rhs instanceof StreamingWindow)
        {
            _r = (StreamingWindow)rhs;
        }

        if(_r != null)
        {
            if(windowId != _r.windowId)
            {
                if(windowId == null || _r.windowId == null || !windowId.equals(_r.windowId))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(datagrams, _r.datagrams))
            {
                return false;
            }
            if(startTimestamp != _r.startTimestamp)
            {
                return false;
            }
            if(endTimestamp != _r.endTimestamp)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::SITM::MIO::StreamingWindow");
        __h = IceInternal.HashUtil.hashAdd(__h, windowId);
        __h = IceInternal.HashUtil.hashAdd(__h, datagrams);
        __h = IceInternal.HashUtil.hashAdd(__h, startTimestamp);
        __h = IceInternal.HashUtil.hashAdd(__h, endTimestamp);
        return __h;
    }

    public StreamingWindow
    clone()
    {
        StreamingWindow c = null;
        try
        {
            c = (StreamingWindow)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(windowId);
        BusDatagramSeqHelper.write(__os, datagrams);
        __os.writeLong(startTimestamp);
        __os.writeLong(endTimestamp);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        windowId = __is.readString();
        datagrams = BusDatagramSeqHelper.read(__is);
        startTimestamp = __is.readLong();
        endTimestamp = __is.readLong();
    }

    static public void
    __write(IceInternal.BasicStream __os, StreamingWindow __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public StreamingWindow
    __read(IceInternal.BasicStream __is, StreamingWindow __v)
    {
        if(__v == null)
        {
             __v = new StreamingWindow();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final StreamingWindow __nullMarshalValue = new StreamingWindow();

    public static final long serialVersionUID = -1245546425L;
}
