// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `VelocityCalculation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM.MIO;

public class VelocityResult implements java.lang.Cloneable, java.io.Serializable
{
    public String arcId;

    public double averageVelocity;

    public int sampleCount;

    public long processingTime;

    public String periodStart;

    public String periodEnd;

    public VelocityResult()
    {
        arcId = "";
        periodStart = "";
        periodEnd = "";
    }

    public VelocityResult(String arcId, double averageVelocity, int sampleCount, long processingTime, String periodStart, String periodEnd)
    {
        this.arcId = arcId;
        this.averageVelocity = averageVelocity;
        this.sampleCount = sampleCount;
        this.processingTime = processingTime;
        this.periodStart = periodStart;
        this.periodEnd = periodEnd;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        VelocityResult _r = null;
        if(rhs instanceof VelocityResult)
        {
            _r = (VelocityResult)rhs;
        }

        if(_r != null)
        {
            if(arcId != _r.arcId)
            {
                if(arcId == null || _r.arcId == null || !arcId.equals(_r.arcId))
                {
                    return false;
                }
            }
            if(averageVelocity != _r.averageVelocity)
            {
                return false;
            }
            if(sampleCount != _r.sampleCount)
            {
                return false;
            }
            if(processingTime != _r.processingTime)
            {
                return false;
            }
            if(periodStart != _r.periodStart)
            {
                if(periodStart == null || _r.periodStart == null || !periodStart.equals(_r.periodStart))
                {
                    return false;
                }
            }
            if(periodEnd != _r.periodEnd)
            {
                if(periodEnd == null || _r.periodEnd == null || !periodEnd.equals(_r.periodEnd))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::SITM::MIO::VelocityResult");
        __h = IceInternal.HashUtil.hashAdd(__h, arcId);
        __h = IceInternal.HashUtil.hashAdd(__h, averageVelocity);
        __h = IceInternal.HashUtil.hashAdd(__h, sampleCount);
        __h = IceInternal.HashUtil.hashAdd(__h, processingTime);
        __h = IceInternal.HashUtil.hashAdd(__h, periodStart);
        __h = IceInternal.HashUtil.hashAdd(__h, periodEnd);
        return __h;
    }

    public VelocityResult
    clone()
    {
        VelocityResult c = null;
        try
        {
            c = (VelocityResult)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(arcId);
        __os.writeDouble(averageVelocity);
        __os.writeInt(sampleCount);
        __os.writeLong(processingTime);
        __os.writeString(periodStart);
        __os.writeString(periodEnd);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        arcId = __is.readString();
        averageVelocity = __is.readDouble();
        sampleCount = __is.readInt();
        processingTime = __is.readLong();
        periodStart = __is.readString();
        periodEnd = __is.readString();
    }

    static public void
    __write(IceInternal.BasicStream __os, VelocityResult __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public VelocityResult
    __read(IceInternal.BasicStream __is, VelocityResult __v)
    {
        if(__v == null)
        {
             __v = new VelocityResult();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final VelocityResult __nullMarshalValue = new VelocityResult();

    public static final long serialVersionUID = 1982074464L;
}
