// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `VelocityCalculation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM.MIO;

/**
 * Provides type-specific helper functions.
 **/
public final class WorkerPrxHelper extends Ice.ObjectPrxHelperBase implements WorkerPrx
{
    private static final String __isAlive_name = "isAlive";

    public boolean isAlive()
    {
        return isAlive(null, false);
    }

    public boolean isAlive(java.util.Map<String, String> __ctx)
    {
        return isAlive(__ctx, true);
    }

    private boolean isAlive(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__isAlive_name);
        return end_isAlive(begin_isAlive(__ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_isAlive()
    {
        return begin_isAlive(null, false, false, null);
    }

    public Ice.AsyncResult begin_isAlive(java.util.Map<String, String> __ctx)
    {
        return begin_isAlive(__ctx, true, false, null);
    }

    public Ice.AsyncResult begin_isAlive(Ice.Callback __cb)
    {
        return begin_isAlive(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_isAlive(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_isAlive(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_isAlive(Callback_Worker_isAlive __cb)
    {
        return begin_isAlive(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_isAlive(java.util.Map<String, String> __ctx, Callback_Worker_isAlive __cb)
    {
        return begin_isAlive(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_isAlive(IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_isAlive(null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_isAlive(IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_isAlive(null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_isAlive(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_isAlive(__ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_isAlive(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_isAlive(__ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_isAlive(java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_isAlive(__ctx, __explicitCtx, __synchronous, 
                             new IceInternal.Functional_TwowayCallbackBool(__responseCb, __exceptionCb, __sentCb)
                                 {
                                     public final void __completed(Ice.AsyncResult __result)
                                     {
                                         WorkerPrxHelper.__isAlive_completed(this, __result);
                                     }
                                 });
    }

    private Ice.AsyncResult begin_isAlive(java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__isAlive_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__isAlive_name, __cb);
        try
        {
            __result.prepare(__isAlive_name, Ice.OperationMode.Idempotent, __ctx, __explicitCtx, __synchronous);
            __result.writeEmptyParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public boolean end_isAlive(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __isAlive_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __isAlive_completed(Ice.TwowayCallbackBool __cb, Ice.AsyncResult __result)
    {
        SITM.MIO.WorkerPrx __proxy = (SITM.MIO.WorkerPrx)__result.getProxy();
        boolean __ret = false;
        try
        {
            __ret = __proxy.end_isAlive(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __processStreamingWindow_name = "processStreamingWindow";

    public VelocityResult processStreamingWindow(StreamingWindow window)
    {
        return processStreamingWindow(window, null, false);
    }

    public VelocityResult processStreamingWindow(StreamingWindow window, java.util.Map<String, String> __ctx)
    {
        return processStreamingWindow(window, __ctx, true);
    }

    private VelocityResult processStreamingWindow(StreamingWindow window, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__processStreamingWindow_name);
        return end_processStreamingWindow(begin_processStreamingWindow(window, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window)
    {
        return begin_processStreamingWindow(window, null, false, false, null);
    }

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, java.util.Map<String, String> __ctx)
    {
        return begin_processStreamingWindow(window, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, Ice.Callback __cb)
    {
        return begin_processStreamingWindow(window, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_processStreamingWindow(window, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, Callback_Worker_processStreamingWindow __cb)
    {
        return begin_processStreamingWindow(window, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, java.util.Map<String, String> __ctx, Callback_Worker_processStreamingWindow __cb)
    {
        return begin_processStreamingWindow(window, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, 
                                                        IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_processStreamingWindow(window, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, 
                                                        IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_processStreamingWindow(window, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_processStreamingWindow(window, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_processStreamingWindow(window, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, 
                                                         java.util.Map<String, String> __ctx, 
                                                         boolean __explicitCtx, 
                                                         boolean __synchronous, 
                                                         IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_processStreamingWindow(window, __ctx, __explicitCtx, __synchronous, 
                                            new IceInternal.Functional_TwowayCallbackArg1<SITM.MIO.VelocityResult>(__responseCb, __exceptionCb, __sentCb)
                                                {
                                                    public final void __completed(Ice.AsyncResult __result)
                                                    {
                                                        WorkerPrxHelper.__processStreamingWindow_completed(this, __result);
                                                    }
                                                });
    }

    private Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, 
                                                         java.util.Map<String, String> __ctx, 
                                                         boolean __explicitCtx, 
                                                         boolean __synchronous, 
                                                         IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__processStreamingWindow_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__processStreamingWindow_name, __cb);
        try
        {
            __result.prepare(__processStreamingWindow_name, Ice.OperationMode.Idempotent, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            StreamingWindow.__write(__os, window);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public VelocityResult end_processStreamingWindow(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __processStreamingWindow_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            VelocityResult __ret = null;
            __ret = VelocityResult.__read(__is, __ret);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __processStreamingWindow_completed(Ice.TwowayCallbackArg1<VelocityResult> __cb, Ice.AsyncResult __result)
    {
        SITM.MIO.WorkerPrx __proxy = (SITM.MIO.WorkerPrx)__result.getProxy();
        VelocityResult __ret = null;
        try
        {
            __ret = __proxy.end_processStreamingWindow(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __processTask_name = "processTask";

    public VelocityResult processTask(ProcessingTask task)
    {
        return processTask(task, null, false);
    }

    public VelocityResult processTask(ProcessingTask task, java.util.Map<String, String> __ctx)
    {
        return processTask(task, __ctx, true);
    }

    private VelocityResult processTask(ProcessingTask task, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__processTask_name);
        return end_processTask(begin_processTask(task, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_processTask(ProcessingTask task)
    {
        return begin_processTask(task, null, false, false, null);
    }

    public Ice.AsyncResult begin_processTask(ProcessingTask task, java.util.Map<String, String> __ctx)
    {
        return begin_processTask(task, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_processTask(ProcessingTask task, Ice.Callback __cb)
    {
        return begin_processTask(task, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_processTask(ProcessingTask task, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_processTask(task, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_processTask(ProcessingTask task, Callback_Worker_processTask __cb)
    {
        return begin_processTask(task, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_processTask(ProcessingTask task, java.util.Map<String, String> __ctx, Callback_Worker_processTask __cb)
    {
        return begin_processTask(task, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_processTask(ProcessingTask task, 
                                             IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_processTask(task, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_processTask(ProcessingTask task, 
                                             IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_processTask(task, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_processTask(ProcessingTask task, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_processTask(task, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_processTask(ProcessingTask task, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_processTask(task, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_processTask(ProcessingTask task, 
                                              java.util.Map<String, String> __ctx, 
                                              boolean __explicitCtx, 
                                              boolean __synchronous, 
                                              IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_processTask(task, __ctx, __explicitCtx, __synchronous, 
                                 new IceInternal.Functional_TwowayCallbackArg1<SITM.MIO.VelocityResult>(__responseCb, __exceptionCb, __sentCb)
                                     {
                                         public final void __completed(Ice.AsyncResult __result)
                                         {
                                             WorkerPrxHelper.__processTask_completed(this, __result);
                                         }
                                     });
    }

    private Ice.AsyncResult begin_processTask(ProcessingTask task, 
                                              java.util.Map<String, String> __ctx, 
                                              boolean __explicitCtx, 
                                              boolean __synchronous, 
                                              IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__processTask_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__processTask_name, __cb);
        try
        {
            __result.prepare(__processTask_name, Ice.OperationMode.Idempotent, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            ProcessingTask.__write(__os, task);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public VelocityResult end_processTask(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __processTask_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            VelocityResult __ret = null;
            __ret = VelocityResult.__read(__is, __ret);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __processTask_completed(Ice.TwowayCallbackArg1<VelocityResult> __cb, Ice.AsyncResult __result)
    {
        SITM.MIO.WorkerPrx __proxy = (SITM.MIO.WorkerPrx)__result.getProxy();
        VelocityResult __ret = null;
        try
        {
            __ret = __proxy.end_processTask(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static WorkerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), WorkerPrx.class, WorkerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static WorkerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), WorkerPrx.class, WorkerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static WorkerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), WorkerPrx.class, WorkerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static WorkerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), WorkerPrx.class, WorkerPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static WorkerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, WorkerPrx.class, WorkerPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static WorkerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, WorkerPrx.class, WorkerPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::SITM::MIO::Worker"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, WorkerPrx v)
    {
        __os.writeProxy(v);
    }

    public static WorkerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            WorkerPrxHelper result = new WorkerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
