// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `VelocityCalculation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM.MIO;

public interface WorkerPrx extends Ice.ObjectPrx
{
    public VelocityResult processTask(ProcessingTask task);

    public VelocityResult processTask(ProcessingTask task, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_processTask(ProcessingTask task);

    public Ice.AsyncResult begin_processTask(ProcessingTask task, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_processTask(ProcessingTask task, Ice.Callback __cb);

    public Ice.AsyncResult begin_processTask(ProcessingTask task, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_processTask(ProcessingTask task, Callback_Worker_processTask __cb);

    public Ice.AsyncResult begin_processTask(ProcessingTask task, java.util.Map<String, String> __ctx, Callback_Worker_processTask __cb);

    public Ice.AsyncResult begin_processTask(ProcessingTask task, 
                                             IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_processTask(ProcessingTask task, 
                                             IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_processTask(ProcessingTask task, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_processTask(ProcessingTask task, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public VelocityResult end_processTask(Ice.AsyncResult __result);

    public boolean isAlive();

    public boolean isAlive(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_isAlive();

    public Ice.AsyncResult begin_isAlive(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_isAlive(Ice.Callback __cb);

    public Ice.AsyncResult begin_isAlive(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_isAlive(Callback_Worker_isAlive __cb);

    public Ice.AsyncResult begin_isAlive(java.util.Map<String, String> __ctx, Callback_Worker_isAlive __cb);

    public Ice.AsyncResult begin_isAlive(IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_isAlive(IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_isAlive(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_isAlive(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_isAlive(Ice.AsyncResult __result);

    public VelocityResult processStreamingWindow(StreamingWindow window);

    public VelocityResult processStreamingWindow(StreamingWindow window, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window);

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, Ice.Callback __cb);

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, Callback_Worker_processStreamingWindow __cb);

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, java.util.Map<String, String> __ctx, Callback_Worker_processStreamingWindow __cb);

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, 
                                                        IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, 
                                                        IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_processStreamingWindow(StreamingWindow window, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_GenericCallback1<VelocityResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb);

    public VelocityResult end_processStreamingWindow(Ice.AsyncResult __result);
}
